#!/bin/bash
# ~/.bash/logout: executed by bash(1) when login shell exits.

# Clear the screen when leaving from root's shell to increase privacy:
if [[ ${EUID} == 0 && ${SHLVL} == 1 ]]; then
  [ -x /usr/bin/clear ] && reset
fi
