#!/bin/bash
# ~/.bash/logout: executed by bash(1) when login shell exits.

# Disable the xhost when leaving, and clear the screen to increase privacy...
if [ "$SHLVL" = 1 ]; then
  #xhost -SI:localuser:root &> /dev/null
  [ -x /usr/bin/clear ] && reset
  #echo "root: xhost has been disabled"
fi
